server:
  port: 8084

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/cropdeal_payments?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASS:root22}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
