server:
  port: 8086

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/cropdeal_admin?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASS:root22}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
